name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "formal_conjectures"
path = "../"

[[require]]
name = "verso"
git = "https://github.com/mo271/verso.git"
rev = "5207ca14f0c419f2268aae29c76ce23b2d4dc340"
